version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    networks:
      - dapr-network
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5

  client-dapr:
    container_name: client-dapr
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "client-app",
      "-dapr-http-port", "3500",
      "-components-path", "/components"
    ]
    volumes:
      - "./components:/components"
      - "./secrets.json:/components/secrets.json"
    networks:
      - dapr-network
    ports:
      - "3500:3500"

  application:
    container_name: application
    build: ./
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    environment:  
      DAPR_CLIENT_HOST: client-dapr
      DAPR_CLIENT_PORT: 3500
      DAPR_SECRET_STORE_NAME: local-secrets
      DAPR_SECRETS_DB_HOST: db-host
      DAPR_SECRETS_DB_PORT: db-port
      DAPR_SECRETS_DB_USER: db-user
      DAPR_SECRETS_DB_PASSWORD: db-password
      DAPR_SECRETS_DB_NAME: db-name
    networks:
      - dapr-network
    ports:
      - "3000:3000"

networks:
  dapr-network:
    driver: bridge